- app/templates/README.md
> Sample code variable name in readme should be safeSlugname

- app/templates/README.md
> Another variable name in readme should be safeSlugname

- app/templates/README.md
daviddm-image is actually daviddm-url and vise versa which is wrong.
> Make variable names match each other

- app/index.js
> prompt: clarify GitHub organization is applicable

- generators/app/index.js
- generators/git/index.js
- generators/git/templates/gitattributes
- generators/git/templates/gitignore
- test/app.js
- test/git.js
Let's hope the second time will be better ;) There we go. `node:git` this time. Ref https://github.com/yeoman/generator-node/issues/66.
> Implement `node:git`

- generators/app/index.js
- generators/jscs/index.js
- generators/jscs/templates/jscsrc
- test/app.js
- test/jscs.js
Ref https://github.com/yeoman/generator-node/issues/66
> Implement `node:jscs`

- generators/app/index.js
- generators/boilerplate/index.js
- generators/boilerplate/templates/index.js
- generators/boilerplate/templates/test.js
- test/app.js
- test/boilerplate.js
- test/gulp.js
> Add node:boilerplate subgenerator

- README.md
Feel free to commit directly to this branch for typos and such. I'll squash everything before merging.
> Update documentation for the new version

- README.md
Also gulp should be "task runner"
Closes #115
> Add Babel to README

- generators/gulp/index.js
> Removed unused gulp task

- README.md
- generators/app/index.js
- generators/cli/index.js
- generators/cli/templates/cli.js
- test/cli.js
Implements a CLI boilerplate to fix https://github.com/yeoman/generator-node/issues/112
I noticed some other issues with the build system on the while. I'll open issues about it but that shouldn't block this.
Fix #122
> Add CLI boilerplate

- generators/gulp/index.js
- generators/gulp/templates/gulpfile.js
> Use isparta for coverage is babel is chosen

- generators/gulp/index.js
> Update gulp-eslint to v1.0.0

- generators/app/index.js
The comment about not handling author field when it's a string no longer applies.
I also joined the type checks into a single if/else.
> Enhance author field handling

- generators/app/index.js
- generators/git/index.js
- package.json
- test/app.js
> Feat git info

- generators/app/index.js
- generators/gulp/index.js
> respect this.options.gulp option in gulp generator

- .eslintrc
- .gitignore
- generators/cli/index.js
- generators/eslint/index.js
- generators/gulp/index.js
- gulpfile.js
- package.json
- test/app.js
I just update my repo of `generator-node` to add watch task https://github.com/yeoman/generator-node/issues/177
And when I try to run `$ gulp` some errors appeared.
Voilà my fixes for each error commit by commit.
Comments appreciated. Wait your go to squash commit.
> Fix gulp tasks for generator

- generators/gulp/index.js
- generators/gulp/templates/gulpfile.js
- gulpfile.js
- package.json
fix #177 
Add task and apply `yo node:gulp` on generator.
> Add watch task to run unit test

- generators/app/index.js
- generators/cli/index.js
- generators/eslint/index.js
- generators/gulp/index.js
- package.json
Doesn't look like deep-extend was doing anything that lodash.merge
couldn't do. Requiring one less dep is nice.
> replce deep-extend with lodash.merge

- generators/app/index.js
- generators/git/index.js
ESLint was warning:
> Expected error to be handled  handle-callback-err
> quiet eslint warnings

- generators/app/index.js
- generators/gulp/index.js
- generators/gulp/templates/gulpfile.js
fix #150
Prepublish script will convert line ending to LF.
> Feat line ending

- generators/eslint/index.js
- generators/gulp/index.js
> Update node:eslint to ESLint v2

- package.json
- yarn.lock
Remove:
+ mocha
+ eslint-config-xo
> Remove mocha from package.json

- .eslintignore
- __tests__/app.js
- __tests__/boilerplate.js
- __tests__/cli.js
- __tests__/editorconfig.js
- __tests__/eslint.js
- __tests__/git.js
- __tests__/readme.js
- generators/app/index.js
- generators/cli/index.js
- generators/eslint/index.js
- generators/git/index.js
- generators/readme/index.js
- package-lock.json
- package.json
- yarn.lock
The prettier integration is done with eslint as I found it to be the more convenient. It allows us to easily enforce the code style in the CI process.
Rel #259
> [Feature] Adding Pre-commit hook and Prettier

- generators/git/index.js
To match up the rest of the generators.
> Update the generator/git to ES6 Class

- __tests__/cli.js
- __tests__/nsp.js
- generators/app/index.js
- generators/cli/index.js
- generators/nsp/index.js
- package.json
[Prepublish is deprecated](https://docs.npmjs.com/misc/scripts#deprecation-note) and time for prepare
> Replace deprecated prepublish by prepublishOnly

- __tests__/app.js
- generators/app/index.js
Now you can be entered versions of nodejs #201
> Customization nodejs version for travis

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/scorecards.yml
Related https://github.com/yeoman/.github/issues/1
> ci: apply security best practices
